<?php
/**
 * about.inc
 * Modal block with some information about the Versions Server and the Version Check plugin for Elgg
 * Author: Federico Mestrone
 * Created: 15/12/2012 12:40
 * Copyright: 2012, Moodsdesign Ltd
 */
?>
<div id="aboutModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="aboutModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="aboutModalLabel">About...</h3>
    </div>
    <div class="modal-body">
        <p>One fine body…</p>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    </div>
</div>
