<?php
/**
 * footer.inc
 * Footer for the Versions Server web application
 * Author: Federico Mestrone
 * Created: 15/12/2012 12:37
 * Copyright: 2012, Moodsdesign Ltd
 */
?>
<div id="footer">
    <div class="container">
        <p class="muted credit">Copyright &copy; 2012, <a href="http://www.moodsdesign.com" target="_blank">Moodsdesign Ltd</a>
            for the <a href="https://moodsdesign.atlassian.net/wiki/display/ELGGVERCHK" target="_blank">Version Check</a> plugin for Elgg.</p>
    </div>
</div>
