<?php
/**
 * head.inc
 * Author: Federico Mestrone
 * Created: 15/12/2012 12:45
 * Copyright: 2012, Moodsdesign Ltd
 */
?>
<meta charset="utf-8">

<title>Versions Server</title>

<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="A Versions Server implementation for the Version Check plugin for Elgg">
<meta name="author" content="Federico Mestrone">
<meta name="copyright" content="2012, Moodsdesign Ltd">

<link href="vendors/bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
<link href="style.css" rel="stylesheet" media="screen">

<script src="vendors/jquery-1.8.3.min.js"></script>
<script src="vendors/bootstrap/js/bootstrap.min.js"></script>
<script src="code.js"></script>
